# Generated by Django 5.2.12 on 2026-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
